### PR TITLE
WIP: Simplistic user-/character system

### PR DESCRIPTION
**Pull request by tbergmueller**
***This PR is still WIP***

A simple and extendable User- and Character system preparing:
- Multiple User-Login methods, either before first spawn or during a game
- Guest users (default, when no login is provided)
- Each user can have
   - Username
   - Own character

After checkout, Users are not authorized, but get assigned different characters:
- Odd Connection-IDs get bot.glb
- Even Connection-IDs get bot.glb wearing a hat.

Limitations:
- This is *not* load-tested beyond 10 concurrent users
- There is currently weird issues when adding `<m-model>` duck to example-mml.html.
  -  If the duck is there, no new users can log in (stuck ad Loading scren). 
  - If the Duck is not there, users can connect normally. if the duck is added (w/o restart) when e.g. 4 users are connected, the duck appears for those four users and they can continue to play normally, but no new users can connect.
  - After the duck is removed form example-mml.html again (without restart), new users can connect again.
  - Since the characters are defined via `<m-character>` my current suspicion is towards a f*ckup in DOM. To be investigated
- Multiple character-updates during an active connection have not been tested yet (should be possible with minor changes, will follow before making this PR final)

playground

**What kind of change does your PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Tests
- [ ] Other, please describe:

### CODE REVIEW

**Comment by MarcusLongmuir** [comment]
Thanks for picking this up! I've had a few thoughts myself about how to do this.

I think the main notes I have at this point are:

* I agree with your approach of making this system extensible with the option of anonymous/pre/during auth methods. The thing I had in mind is that it would be good if the server that renders the page with the client on it could be responsible for generating a connection token that is then sent to the websocket as the first message before any communication actually occurs. This means that the auth could happen _before_ the client is rendered and can be decoupled from the experience. It's up to the network server how to handle the validation of that token.

* I think we'd like to support using arbitrary MML document URLs for each user and also the ability to update that along with other parts of your identity such as display name / more complex payload. I think you're on the same lines already with the `USER_UPDATE` message.

Happy to chat some more about this 👍

**Comment by tbergmueller** [comment]
Thank you for the swift comment @MarcusLongmuir !

> Happy to chat some more about this 👍
I pinged you on Discord - do you prefer a quick 1:1 discussion or shall we discuss here in the PR?

**Comment by MarcusLongmuir** [comment]
@tbergmueller. Thanks for the discussion. I think the main flow to get working is:

Assume the user has already completed an authentication step before they arrive at the HTML page that includes the 3d-web-experience client.

1. The server that renders the 3d-web-experience client HTML page generates a token (likely a JWT) that includes a user id, display name, and an MML character string/url. This token is then included on the page as a window property that is accessible to the client bundle. (e.g. `window.USER_AUTH_TOKEN = "SOME.TOKEN"`). This page is currently served (without injecting anything) by [this line](https://github.com/mml-io/3d-web-experience/blob/d6eaef0603686b87bf442c85c8cef69398c230dc/example/server/src/router/web-app-routes.ts#L26).

2. The client bundle finds the window property when it starts and uses this token as the payload of a first message to the websocket server (likely injected [around here](https://github.com/mml-io/3d-web-experience/blob/d6eaef0603686b87bf442c85c8cef69398c230dc/example/web-client/src/index.ts#L143)). The protocol is therefore changed to expect the user to send this first token message. If the server is configured to allow anonymous users then this token could be empty, but the message is still expected.

3. The server responds to the client with a message indicating which user id this client has, and sends an update to all clients that this new joiner client has connected and has a particular display name and MML character string. I think this can just be an extension of the `IDENTITY_MESSAGE` [here](https://github.com/mml-io/3d-web-experience/blob/d6eaef0603686b87bf442c85c8cef69398c230dc/packages/3d-web-user-networking/src/messages.ts#L12).

4. The connecting client (and all others) receive this message describing the identity of the new joiner and associate the display name with the user id and load the MML character string (potentially using a cache if another user had already used this same URL).

**Comment by tbergmueller** [comment]
I did a complete rewrite considering our discussions here in the PR and following our call / written discussions. 
It is available here: https://github.com/mml-io/3d-web-experience/pull/122 

I will close this PR.

**Pull request closed without merging**
